### ISSUE TITLE
python のプログラムが動かない

### ISSUE THREAD

**Issue by M-Onitsuka** [jsk-enshu/robot-programming#106]
```
[ERROR] [WallTime: 1477637749.411129] [305.800000] bad callback: <function cb at 0x7f72bf993cf8>
Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/topics.py", line 720, in _invoke_callback
    cb(msg)
  File "test.py", line 13, in cb
    pub.publish(marker)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/topics.py", line 856, in publish
    raise ROSSerializationException(str(e))
ROSSerializationException: field type must be an integer type
```

ソースコードは

```
#!/usr/bin/env python

import rospy
from opencv_apps.msg import RotatedRectStamped
from image_view2.msg import ImageMarker2
from geometry_msgs.msg import Point

def cb(msg):
    print msg.rect
    marker = ImageMarker2()
    marker.type = ()
    marker.position = Point(msg.rect.center.x, msg.rect.center.y, 0)
    pub.publish(marker)


rospy.init_node('client')
rospy.Subscriber('/camshift/track_box',RotatedRectStamped,cb)
pub = rospy.Publisher('/image_marker', ImageMarker2)
rospy.spin()
```

**Comment by M-Onitsuka** [comment]
```
    marker.type = ()
```
がおかしい．
```
    marker.type = 0
```
とするとよさそう
