### ISSUE TITLE
catkin build が通りません

### ISSUE THREAD

**Issue by poyotamu000** [jsk-enshu/robot-programming#273]
以下のようにエラーが出ます。

```
mech-user@KI00125:~/catkin_ws$ catkin build
--------------------------------------------------------------
Profile:                     default
Extending:          [cached] /opt/ros/melodic
Workspace:                   /home/mech-user/catkin_ws
--------------------------------------------------------------
Build Space:        [exists] /home/mech-user/catkin_ws/build
Devel Space:        [exists] /home/mech-user/catkin_ws/devel
Install Space:      [unused] /home/mech-user/catkin_ws/install
Log Space:          [exists] /home/mech-user/catkin_ws/logs
Source Space:       [exists] /home/mech-user/catkin_ws/src
DESTDIR:            [unused] None
--------------------------------------------------------------
Devel Space Layout:          linked
Install Space Layout:        None
--------------------------------------------------------------
Additional CMake Args:       None
Additional Make Args:        None
Additional catkin Make Args: None
Internal Make Job Server:    True
Cache Job Environments:      False
--------------------------------------------------------------
Whitelisted Packages:        None
Blacklisted Packages:        None
--------------------------------------------------------------
Workspace configuration appears valid.
--------------------------------------------------------------
[build] Found '40' packages in 0.0 seconds.                                    
[build] Package table is up to date.                                           
Starting  >>> beginner_tutorials                                               
Starting  >>> dynamixel_7dof_arm                                               
Starting  >>> dynamixel_urdf                                                   
Starting  >>> kobuki_auto_docking                                              
Starting  >>> kobuki_bumper2pc                                                 
Starting  >>> kobuki_controller_tutorial                                       
Starting  >>> kobuki_dashboard                                                 
Starting  >>> kobuki_description                                               
Finished  <<< kobuki_dashboard                          [ 0.1 seconds ]        
Starting  >>> kobuki_gazebo_plugins                                            
Finished  <<< kobuki_description                        [ 0.2 seconds ]        
Finished  <<< dynamixel_7dof_arm                        [ 0.2 seconds ]        
Starting  >>> kobuki_keyop                                                     
Starting  >>> kobuki_random_walker                                             
Finished  <<< beginner_tutorials                        [ 0.4 seconds ]        
Starting  >>> kobuki_rviz_launchers                                            
Finished  <<< dynamixel_urdf                            [ 0.2 seconds ]        
Starting  >>> kobuki_safety_controller                                         
Finished  <<< kobuki_rviz_launchers                     [ 0.2 seconds ]        
Finished  <<< kobuki_controller_tutorial                [ 1.2 seconds ]        
Finished  <<< kobuki_bumper2pc                          [ 1.5 seconds ]        
Finished  <<< kobuki_random_walker                      [ 1.3 seconds ]        
Finished  <<< kobuki_keyop                              [ 1.2 seconds ]        
Finished  <<< kobuki_auto_docking                       [ 1.7 seconds ]        
Finished  <<< kobuki_safety_controller                  [ 1.2 seconds ]        
Starting  >>> turtlebot_capabilities                                           
Starting  >>> turtlebot_msgs                                                   
Starting  >>> turtleboteus                                                     
Starting  >>> turtlebot_description                                            
Starting  >>> kobuki_rapps                                                     
Finished  <<< kobuki_gazebo_plugins                     [ 1.7 seconds ]        
Starting  >>> kobuki_gazebo                                                    
Finished  <<< kobuki_rapps                              [ 0.2 seconds ]        
Starting  >>> kobuki_node                                                      
Finished  <<< turtlebot_description                     [ 0.2 seconds ]        
Finished  <<< turtleboteus                              [ 0.2 seconds ]        
Finished  <<< turtlebot_capabilities                    [ 0.1 seconds ]        
Finished  <<< kobuki_gazebo                             [ 0.2 seconds ]        
Finished  <<< turtlebot_msgs                            [ 0.3 seconds ]        
Finished  <<< kobuki_node                               [ 0.6 seconds ]        
Starting  >>> kobuki_capabilities                                              
Starting  >>> kobuki_testsuite                                                 
Finished  <<< kobuki_testsuite                          [ 0.1 seconds ]        
Starting  >>> kobuki_qtestsuite                                                
Finished  <<< kobuki_capabilities                       [ 0.1 seconds ]        
Starting  >>> turtlebot_bringup                                                
Finished  <<< turtlebot_bringup                         [ 0.1 seconds ]        
Starting  >>> turtlebot_actions                                                
Starting  >>> turtlebot_calibration                                            
Starting  >>> turtlebot_navigation                                             
Starting  >>> turtlebot_teleop                                                 
Finished  <<< turtlebot_teleop                          [ 0.2 seconds ]        
Starting  >>> turtlebot_follower                                               
Finished  <<< turtlebot_navigation                      [ 0.3 seconds ]        
Finished  <<< turtlebot_calibration                     [ 0.4 seconds ]        
Starting  >>> turtlebot_gazebo                                                 
Starting  >>> turtlebot_stage                                                  
Starting  >>> turtlebot_stdr                                                   
Starting  >>> dxl_armed_turtlebot                                              
_______________________________________________________________________________
Errors     << turtlebot_follower:make /home/mech-user/catkin_ws/logs/turtlebot_follower/build.make.006.log
Traceback (most recent call last):
  File "/home/mech-user/catkin_ws/src/turtlebot_apps/turtlebot_follower/cfg/Follower.cfg", line 39, in <module>
    from dynamic_reconfigure.parameter_generator_catkin import *
  File "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/__init__.py", line 38, in <module>
    import roslib
  File "/opt/ros/melodic/lib/python2.7/dist-packages/roslib/__init__.py", line 50, in <module>
    from roslib.launcher import load_manifest
  File "/opt/ros/melodic/lib/python2.7/dist-packages/roslib/launcher.py", line 42, in <module>
    import rospkg
ModuleNotFoundError: No module named 'rospkg'
make[2]: *** [/home/mech-user/catkin_ws/devel/.private/turtlebot_follower/include/turtlebot_follower/FollowerConfig.h] Error 1
make[1]: *** [CMakeFiles/turtlebot_follower_gencfg.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make: *** [all] Error 2
cd /home/mech-user/catkin_ws/build/turtlebot_follower; catkin build --get-env turtlebot_follower | catkin env -si  /usr/bin/make --jobserver-fds=6,7 -j; cd -
...............................................................................
Failed     << turtlebot_follower:make                   [ Exited with code 2 ] 
Failed    <<< turtlebot_follower                        [ 0.3 seconds ]        
Abandoned <<< turtlebot_rapps                           [ Unrelated job failed ]
Abandoned <<< daisya_euslisp_tutorials                  [ Unrelated job failed ]
Finished  <<< turtlebot_gazebo                          [ 0.2 seconds ]        
Finished  <<< kobuki_qtestsuite                         [ 1.1 seconds ]        
Finished  <<< turtlebot_stage                           [ 0.2 seconds ]        
Finished  <<< turtlebot_stdr                            [ 0.2 seconds ]        
Finished  <<< dxl_armed_turtlebot                       [ 0.2 seconds ]        
_______________________________________________________________________________
Errors     << turtlebot_actions:make /home/mech-user/catkin_ws/logs/turtlebot_actions/build.make.006.log
/usr/bin/ld: warning: libopencv_flann.so.3.2, needed by /usr/lib/x86_64-linux-gnu/libopencv_calib3d.so.3.2.0, may conflict with libopencv_flann.so.3.4
/usr/bin/ld: warning: libopencv_imgproc.so.3.4, needed by /home/mech-user/anaconda3/lib/libopencv_dnn.so.3.4.2, may conflict with libopencv_imgproc.so.3.2
/usr/lib/x86_64-linux-gnu/libopencv_imgcodecs.so.3.2.0: undefined reference to `TIFFReadDirectory@LIBTIFF_4.0'
//usr/lib/libgdal.so.20: undefined reference to `TIFFLastDirectory@LIBTIFF_4.0'
/usr/lib/x86_64-linux-gnu/libopencv_imgcodecs.so.3.2.0: undefined reference to `TIFFWriteEncodedStrip@LIBTIFF_4.0'
/usr/lib/x86_64-linux-gnu/libopencv_imgcodecs.so.3.2.0: undefined reference to `TIFFIsTiled@LIBTIFF_4.0'
//usr/lib/libgdal.so.20: undefined reference to `TIFFSwabArrayOfShort@LIBTIFF_4.0'
//usr/lib/libgdal.so.20: undefined reference to `TIFFIsByteSwapped@LIBTIFF_4.0'
//usr/lib/libgdal.so.20: undefined reference to `TIFFFlushData@LIBTIFF_4.0'
//usr/lib/libgdal.so.20: undefined reference to `TIFFFreeDirectory@LIBTIFF_4.0'
/usr/lib/x86_64-linux-gnu/libopencv_imgcodecs.so.3.2.0: undefined reference to `TIFFScanlineSize@LIBTIFF_4.0'
//usr/lib/libgdal.so.20: undefined reference to `TIFFWriteEncodedTile@LIBTIFF_4.0'
//usr/lib/libgdal.so.20: undefined reference to `TIFFWriteBufferSetup@LIBTIFF_4.0'
//usr/lib/libgdal.so.20: undefined reference to `TIFFTileSize@LIBTIFF_4.0'
/usr/lib/x86_64-linux-gnu/libopencv_imgcodecs.so.3.2.0: undefined reference to `TIFFRGBAImageOK@LIBTIFF_4.0'
/usr/lib/x86_64-linux-gnu/libopencv_imgcodecs.so.3.2.0: undefined reference to `TIFFClose@LIBTIFF_4.0'
//usr/lib/libgdal.so.20: undefined reference to `TIFFWriteRawStrip@LIBTIFF_4.0'
//usr/lib/libgdal.so.20: undefined reference to `TIFFSetTagExtender@LIBTIFF_4.0'
//usr/lib/libgdal.so.20: undefined reference to `TIFFGetFieldDefaulted@LIBTIFF_4.0'
//usr/lib/libgdal.so.20: undefined reference to `TIFFSwabArrayOfLong@LIBTIFF_4.0'
//usr/lib/libgdal.so.20: undefined reference to `TIFFTileSize64@LIBTIFF_4.0'
//usr/lib/libgdal.so.20: undefined reference to `TIFFReadRGBATileExt@LIBTIFF_4.0'
//usr/lib/libgdal.so.20: undefined reference to `TIFFStripSize@LIBTIFF_4.0'
//usr/lib/libgdal.so.20: undefined reference to `TIFFMergeFieldInfo@LIBTIFF_4.0'
/usr/lib/x86_64-linux-gnu/libopencv_imgcodecs.so.3.2.0: undefined reference to `TIFFSetWarningHandler@LIBTIFF_4.0'
//usr/lib/libgdal.so.20: undefined reference to `TIFFGetConfiguredCODECs@LIBTIFF_4.0'
//usr/lib/x86_64-linux-gnu/libgeotiff.so.2: undefined reference to `_TIFFmalloc@LIBTIFF_4.0'
//usr/lib/x86_64-linux-gnu/libgeotiff.so.2: undefined reference to `_TIFFmemcpy@LIBTIFF_4.0'
//usr/lib/libgdal.so.20: undefined reference to `TIFFClientdata@LIBTIFF_4.0'
//usr/lib/x86_64-linux-gnu/libgeotiff.so.2: undefined reference to `_TIFFrealloc@LIBTIFF_4.0'
//usr/lib/x86_64-linux-gnu/libgeotiff.so.2: undefined reference to `_TIFFmemset@LIBTIFF_4.0'
//usr/lib/libgdal.so.20: undefined reference to `TIFFReadRGBAStripExt@LIBTIFF_4.0'
//usr/lib/libgdal.so.20: undefined reference to `TIFFWriteCheck@LIBTIFF_4.0'
//usr/lib/libgdal.so.20: undefined reference to `TIFFSetWriteOffset@LIBTIFF_4.0'
//usr/lib/libgdal.so.20: undefined reference to `TIFFDefaultStripSize@LIBTIFF_4.0'
//usr/lib/libgdal.so.20: undefined reference to `TIFFScanlineSize64@LIBTIFF_4.0'
//usr/lib/libgdal.so.20: undefined reference to `TIFFIsBigEndian@LIBTIFF_4.0'
//usr/lib/x86_64-linux-gnu/libpoppler.so.73: undefined reference to `TIFFFdOpen@LIBTIFF_4.0'
/usr/lib/x86_64-linux-gnu/libopencv_imgcodecs.so.3.2.0: undefined reference to `TIFFWriteScanline@LIBTIFF_4.0'
//usr/lib/libgdal.so.20: undefined reference to `_TIFFfree@LIBTIFF_4.0'
//usr/lib/libgdal.so.20: undefined reference to `TIFFSwabLong@LIBTIFF_4.0'
/usr/lib/x86_64-linux-gnu/libopencv_imgcodecs.so.3.2.0: undefined reference to `TIFFGetField@LIBTIFF_4.0'
//usr/lib/libgdal.so.20: undefined reference to `TIFFSwabShort@LIBTIFF_4.0'
/usr/lib/x86_64-linux-gnu/libopencv_imgcodecs.so.3.2.0: undefined reference to `TIFFNumberOfStrips@LIBTIFF_4.0'
//usr/lib/libgdal.so.20: undefined reference to `TIFFWriteDirectory@LIBTIFF_4.0'
//usr/lib/x86_64-linux-gnu/libgdcmMSFF.so.2.8: undefined reference to `uuid_generate@UUID_1.0'
/usr/lib/x86_64-linux-gnu/libopencv_imgcodecs.so.3.2.0: undefined reference to `TIFFReadEncodedTile@LIBTIFF_4.0'
/usr/lib/x86_64-linux-gnu/libopencv_imgcodecs.so.3.2.0: undefined reference to `TIFFReadRGBATile@LIBTIFF_4.0'
//usr/lib/x86_64-linux-gnu/libgeotiff.so.2: undefined reference to `TIFFClientOpen@LIBTIFF_4.0'
//usr/lib/libgdal.so.20: undefined reference to `TIFFFlush@LIBTIFF_4.0'
//usr/lib/x86_64-linux-gnu/libgdcmMSFF.so.2.8: undefined reference to `uuid_parse@UUID_1.0'
//usr/lib/libgdal.so.20: undefined reference to `TIFFErrorExt@LIBTIFF_4.0'
//usr/lib/libgdal.so.20: undefined reference to `TIFFNumberOfDirectories@LIBTIFF_4.0'
//usr/lib/libgdal.so.20: undefined reference to `TIFFWriteRawTile@LIBTIFF_4.0'
//usr/lib/libgdal.so.20: undefined reference to `TIFFStripSize64@LIBTIFF_4.0'
//usr/lib/libgdal.so.20: undefined reference to `TIFFCreateDirectory@LIBTIFF_4.0'
/usr/lib/x86_64-linux-gnu/libopencv_imgcodecs.so.3.2.0: undefined reference to `TIFFOpen@LIBTIFF_4.0'
//usr/lib/libgdal.so.20: undefined reference to `TIFFSwabArrayOfDouble@LIBTIFF_4.0'
//usr/lib/libgdal.so.20: undefined reference to `TIFFSetSubDirectory@LIBTIFF_4.0'
//usr/lib/libgdal.so.20: undefined reference to `TIFFUnlinkDirectory@LIBTIFF_4.0'
/usr/lib/x86_64-linux-gnu/libopencv_imgcodecs.so.3.2.0: undefined reference to `TIFFReadEncodedStrip@LIBTIFF_4.0'
/usr/lib/x86_64-linux-gnu/libopencv_imgcodecs.so.3.2.0: undefined reference to `TIFFSetField@LIBTIFF_4.0'
//usr/lib/libgdal.so.20: undefined reference to `TIFFCurrentDirOffset@LIBTIFF_4.0'
//usr/lib/libgdal.so.20: undefined reference to `TIFFIsCODECConfigured@LIBTIFF_4.0'
//usr/lib/libgdal.so.20: undefined reference to `TIFFUnsetField@LIBTIFF_4.0'
//usr/lib/libgdal.so.20: undefined reference to `TIFFDataWidth@LIBTIFF_4.0'
//usr/lib/x86_64-linux-gnu/libgdcmMSFF.so.2.8: undefined reference to `uuid_unparse@UUID_1.0'
//usr/lib/libgdal.so.20: undefined reference to `TIFFRewriteDirectory@LIBTIFF_4.0'
//usr/lib/libgdal.so.20: undefined reference to `TIFFGetSizeProc@LIBTIFF_4.0'
/usr/lib/x86_64-linux-gnu/libopencv_imgcodecs.so.3.2.0: undefined reference to `TIFFSetErrorHandler@LIBTIFF_4.0'
//usr/lib/libgdal.so.20: undefined reference to `TIFFSetDirectory@LIBTIFF_4.0'
//usr/lib/libgdal.so.20: undefined reference to `TIFFReadScanline@LIBTIFF_4.0'
//usr/lib/libgdal.so.20: undefined reference to `TIFFNumberOfTiles@LIBTIFF_4.0'
/usr/lib/x86_64-linux-gnu/libopencv_imgcodecs.so.3.2.0: undefined reference to `TIFFReadRGBAStrip@LIBTIFF_4.0'
collect2: error: ld returned 1 exit status
make[2]: *** [/home/mech-user/catkin_ws/devel/.private/turtlebot_actions/lib/turtlebot_actions/find_fiducial_pose] Error 1
make[1]: *** [CMakeFiles/find_fiducial_pose.dir/all] Error 2
make: *** [all] Error 2
cd /home/mech-user/catkin_ws/build/turtlebot_actions; catkin build --get-env turtlebot_actions | catkin env -si  /usr/bin/make --jobserver-fds=6,7 -j; cd -
...............................................................................
Failed     << turtlebot_actions:make                    [ Exited with code 2 ] 
Failed    <<< turtlebot_actions                         [ 1.7 seconds ]        
[build] Summary: 31 of 35 packages succeeded.                                  
[build]   Ignored:   5 packages were skipped or are blacklisted.               
[build]   Warnings:  None.                                                     
[build]   Abandoned: 2 packages were abandoned.                                
[build]   Failed:    2 packages failed.                                        
[build] Runtime: 5.8 seconds total. 
```

**Comment by poyotamu000** [comment]
アナコンダを外したら動きました。
