### ISSUE TITLE
turtlebot_checkerboard.launchが上手く実行できません。

### ISSUE THREAD

**Issue by ham-sh** [jsk-enshu/robot-programming#361]
~/catkin_wsフォルダにおいてある、turtlebot_checkerboard.launchを実行しようとしたのですが、RVizが立ち上がりませんでした。

$ catkin build
$ source ~/catkin_ws/devel/setup.bash
した後に、
$ roslaunch turtlebot_checkerboard.launch
とすると、以下のようなエラーが出てしまいました。
KeyboardInterruptなどと出ていますが、キーボードは触っていません。

... logging to /home/mech-user/.ros/log/4770aa0c-1d0a-11eb-8e48-2079185f7e13/roslaunch-ki00118-29026.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

Deprecated: xacro tag 'kobuki' w/o 'xacro:' xml namespace prefix (will be forbidden in Noetic)
when processing file: /home/mech-user/catkin_ws/src/robot-programming/dxl_armed_turtlebot/urdf/robot.urdf.xacro
Use the following command to fix incorrect tag usage:
find . -iname "*.xacro" | xargs sed -i 's#<\([/]\?\)\(if\|unless\|include\|arg\|property\|macro\|insert_block\)#<\1xacro:\2#g'

xacro.py is deprecated; please use xacro instead
started roslaunch server http://ki00118:36713/

SUMMARY
========

PARAMETERS
 * /camera/rgb/display: 1
 * /camera/rgb/frame_id: camera_rgb_optica...
 * /camera/rgb/grid0_size_x: 7
 * /camera/rgb/grid0_size_y: 4
 * /camera/rgb/objectdetection_tf_publisher/use_simple_tf: True
 * /camera/rgb/rect0_size_x: 0.02
 * /camera/rgb/rect0_size_y: 0.02
 * /camera/rgb/rotation0: 1.0 0.0 0.0 0.0 -...
 * /camera/rgb/single: 1
 * /camera/rgb/translation0: 0 0 0
 * /camera/rgb/type0: test_object
 * /cmd_vel_mux/yaml_cfg_file: /home/mech-user/c...
 * /depthimage_to_laserscan/output_frame_id: /camera_depth_frame
 * /depthimage_to_laserscan/range_min: 0.45
 * /depthimage_to_laserscan/scan_height: 10
 * /fullbody_controller/action_monitor_rate: 100
 * /fullbody_controller/constraints/arm_joint1/goal: 0.02
 * /fullbody_controller/constraints/arm_joint2/goal: 0.02
 * /fullbody_controller/constraints/arm_joint3/goal: 0.02
 * /fullbody_controller/constraints/arm_joint4/goal: 0.02
 * /fullbody_controller/constraints/arm_joint5/goal: 0.02
 * /fullbody_controller/constraints/arm_joint6/goal: 0.02
 * /fullbody_controller/constraints/goal_time: 0.5
 * /fullbody_controller/constraints/stopped_velocity_tolerance: 0.02
 * /fullbody_controller/gains/arm_joint1/d: 0.0
 * /fullbody_controller/gains/arm_joint1/i: 0.0
 * /fullbody_controller/gains/arm_joint1/p: 25.0
 * /fullbody_controller/gains/arm_joint2/d: 0.0
 * /fullbody_controller/gains/arm_joint2/i: 0.0
 * /fullbody_controller/gains/arm_joint2/p: 25.0
 * /fullbody_controller/gains/arm_joint3/d: 0.0
 * /fullbody_controller/gains/arm_joint3/i: 0.0
 * /fullbody_controller/gains/arm_joint3/p: 25.0
 * /fullbody_controller/gains/arm_joint4/d: 0.0
 * /fullbody_controller/gains/arm_joint4/i: 0.0
 * /fullbody_controller/gains/arm_joint4/p: 25.0
 * /fullbody_controller/gains/arm_joint5/d: 0.0
 * /fullbody_controller/gains/arm_joint5/i: 0.0
 * /fullbody_controller/gains/arm_joint5/p: 25.0
 * /fullbody_controller/gains/arm_joint6/d: 0.0
 * /fullbody_controller/gains/arm_joint6/i: 0.0
 * /fullbody_controller/gains/arm_joint6/p: 25.0
 * /fullbody_controller/joints: ['arm_joint1', 'a...
 * /fullbody_controller/state_publish_rate: 100
 * /fullbody_controller/stop_trajectory_duration: 0
 * /fullbody_controller/type: velocity_controll...
 * /gazebo/enable_ros_network: True
 * /gripper_controller/action_monitor_rate: 100
 * /gripper_controller/constraints/goal_time: 0.5
 * /gripper_controller/constraints/gripper_joint/goal: 0.02
 * /gripper_controller/constraints/stopped_velocity_tolerance: 0.02
 * /gripper_controller/gains/gripper_joint/d: 0.0
 * /gripper_controller/gains/gripper_joint/i: 0.0
 * /gripper_controller/gains/gripper_joint/p: 10.0
 * /gripper_controller/joints: ['gripper_joint']
 * /gripper_controller/state_publish_rate: 100
 * /gripper_controller/stop_trajectory_duration: 0
 * /gripper_controller/type: velocity_controll...
 * /joint_state_controller/publish_rate: 50
 * /joint_state_controller/type: joint_state_contr...
 * /robot_description: <?xml version="1....
 * /robot_state_publisher/publish_frequency: 30.0
 * /rosdistro: melodic
 * /rosversion: 1.14.9
 * /use_sim_time: True

NODES
  /
    cmd_vel_mux (nodelet/nodelet)
    cmd_vel_renamer (topic_tools/relay)
    controller_spawner (controller_manager/spawner)
    depthimage_to_laserscan (depthimage_to_laserscan/depthimage_to_laserscan)
    gazebo (gazebo_ros/gzserver)
    gazebo_gui (gazebo_ros/gzclient)
    mobile_base_nodelet_manager (nodelet/nodelet)
    robot_state_publisher (robot_state_publisher/robot_state_publisher)
    rviz (rviz/rviz)
    teleop_twist_keyboard (teleop_twist_keyboard/teleop_twist_keyboard.py)
    tuck_arm (dxl_armed_turtlebot/tuck_arm.py)
    urdf_spawner (gazebo_ros/spawn_model)
  /camera/rgb/
    checkerboard_detector (checkerboard_detector/checkerboard_detector)
    objectdetection_tf_publisher (checkerboard_detector/objectdetection_tf_publisher.py)

WARNING: unrecognized tag sphinxdoc
ROS_MASTER_URI=http://localhost:11311

process[robot_state_publisher-1]: started with pid [29044]
process[cmd_vel_renamer-2]: started with pid [29045]
process[rviz-3]: started with pid [29051]
process[gazebo-4]: started with pid [29057]
process[gazebo_gui-5]: started with pid [29063]
process[urdf_spawner-6]: started with pid [29068]
process[depthimage_to_laserscan-7]: started with pid [29069]
process[mobile_base_nodelet_manager-8]: started with pid [29070]
process[cmd_vel_mux-9]: started with pid [29071]
process[controller_spawner-10]: started with pid [29078]
process[tuck_arm-11]: started with pid [29084]
process[camera/rgb/checkerboard_detector-12]: started with pid [29085]
process[camera/rgb/objectdetection_tf_publisher-13]: started with pid [29086]
RLException: Roslaunch got a 'No such file or directory' error while attempting to run:

xterm -e /opt/ros/melodic/lib/teleop_twist_keyboard/teleop_twist_keyboard.py __name:=teleop_twist_keyboard __log:=/home/mech-user/.ros/log/4770aa0c-1d0a-11eb-8e48-2079185f7e13/teleop_twist_keyboard-14.log

Please make sure that all the executables in this command exist and have
executable permission. This is often caused by a bad launch-prefix.
The traceback for the exception was written to the log file
[teleop_twist_keyboard-14] killing on exit
[camera/rgb/objectdetection_tf_publisher-13] killing on exit
Traceback (most recent call last):
  File "/opt/ros/melodic/lib/checkerboard_detector/objectdetection_tf_publisher.py", line 2, in <module>
    import rospy
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/__init__.py", line 47, in <module>
    from std_msgs.msg import Header
  File "/opt/ros/melodic/lib/python2.7/dist-packages/std_msgs/msg/__init__.py", line 1, in <module>
    from ._Bool import *
  File "/opt/ros/melodic/lib/python2.7/dist-packages/std_msgs/msg/_Bool.py", line 6, in <module>
    import genpy
  File "/opt/ros/melodic/lib/python2.7/dist-packages/genpy/__init__.py", line 34, in <module>
    from . message import Message, SerializationError, DeserializationError, MessageException, struct_I
  File "/opt/ros/melodic/lib/python2.7/dist-packages/genpy/message.py", line 48, in <module>
    import yaml
  File "/usr/lib/python2.7/dist-packages/yaml/__init__.py", line 9, in <module>
    from dumper import *
  File "/usr/lib/python2.7/dist-packages/yaml/dumper.py", line 4, in <module>
    from emitter import *
  File "/usr/lib/python2.7/dist-packages/yaml/emitter.py", line 35, in <module>
    class Emitter(object):
  File "/usr/lib/python2.7/dist-packages/yaml/emitter.py", line 435, in Emitter
    def check_empty_document(self):
KeyboardInterrupt
[camera/rgb/checkerboard_detector-12] killing on exit
[tuck_arm-11] killing on exit
[controller_spawner-10] killing on exit
Traceback (most recent call last):
  File "/opt/ros/melodic/lib/controller_manager/spawner", line 38, in <module>
    import rospy, sys
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/__init__.py", line 47, in <module>
    from std_msgs.msg import Header
  File "/opt/ros/melodic/lib/python2.7/dist-packages/std_msgs/msg/__init__.py", line 28, in <module>
    from ._UInt32MultiArray import *
  File "/opt/ros/melodic/lib/python2.7/dist-packages/std_msgs/msg/_UInt32MultiArray.py", line 2, in <module>
    """autogenerated by genpy from std_msgs/UInt32MultiArray.msg. Do not edit."""
KeyboardInterrupt
Traceback (most recent call last):
  File "/home/mech-user/catkin_ws/src/robot-programming/dxl_armed_turtlebot/scripts/tuck_arm.py", line 4, in <module>
    import rospy
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/__init__.py", line 47, in <module>
    from std_msgs.msg import Header
  File "/opt/ros/melodic/lib/python2.7/dist-packages/std_msgs/msg/__init__.py", line 9, in <module>
    from ._Float32MultiArray import *
  File "/opt/ros/melodic/lib/python2.7/dist-packages/std_msgs/msg/_Float32MultiArray.py", line 2, in <module>
    """autogenerated by genpy from std_msgs/Float32MultiArray.msg. Do not edit."""
KeyboardInterrupt
[cmd_vel_mux-9] killing on exit
[mobile_base_nodelet_manager-8] killing on exit
[depthimage_to_laserscan-7] killing on exit
[urdf_spawner-6] killing on exit
Traceback (most recent call last):
  File "/opt/ros/melodic/lib/gazebo_ros/spawn_model", line 20, in <module>
    import rospy
KeyboardInterrupt
[gazebo-4] killing on exit
Traceback (most recent call last):
  File "/opt/ros/melodic/bin/catkin_find", line 12, in <module>
    from catkin.find_in_workspaces import find_in_workspaces  # noqa: E402
  File "/opt/ros/melodic/lib/python2.7/dist-packages/catkin/find_in_workspaces.py", line 39, in <module>
    from catkin_pkg.packages import find_packages
  File "/usr/lib/python2.7/dist-packages/catkin_pkg/packages.py", line 38, in <module>
[gazebo_gui-5] killing on exit
    from .package import _get_package_xml
  File "/usr/lib/python2.7/dist-packages/catkin_pkg/package.py", line 43, in <module>
    from catkin_pkg.condition import evaluate_condition
  File "/usr/lib/python2.7/dist-packages/catkin_pkg/condition.py", line 17, in <module>
    import pyparsing as pp
  File "/usr/lib/python2.7/dist-packages/pyparsing.py", line 2482, in <module>
Traceback (most recent call last):
  File "/opt/ros/melodic/bin/catkin_find", line 57, in <module>
    main()
  File "/opt/ros/melodic/bin/catkin_find", line 42, in main
    class CaselessLiteral(Literal):
KeyboardInterrupt
    results = find_in_workspaces(args.install_folders, args.project, args.path, first_matching_workspace_only=args.without_underlays, first_match_only=args.first_only, considered_paths=checked)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/catkin/find_in_workspaces.py", line 149, in find_in_workspaces
    source_path_to_packages[source_path] = find_packages(source_path)
  File "/usr/lib/python2.7/dist-packages/catkin_pkg/packages.py", line 87, in find_packages
    packages = find_packages_allowing_duplicates(basepath, exclude_paths=exclude_paths, exclude_subspaces=exclude_subspaces, warnings=warnings)
  File "/usr/lib/python2.7/dist-packages/catkin_pkg/packages.py", line 148, in find_packages_allowing_duplicates
    xml, filename=filename, warnings=warnings)
  File "/usr/lib/python2.7/dist-packages/catkin_pkg/package.py", line 596, in parse_package_string
    root = dom.parseString(data)
  File "/usr/lib/python2.7/xml/dom/minidom.py", line 1927, in parseString
    from xml.dom import expatbuilder
  File "/usr/lib/python2.7/xml/dom/expatbuilder.py", line 561, in <module>
    class Skipper(FilterCrutch):
KeyboardInterrupt
[rviz-3] killing on exit
[cmd_vel_renamer-2] killing on exit
[robot_state_publisher-1] killing on exit
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::lock_error> >'
  what():  boost: mutex lock failed in pthread_mutex_lock: Invalid argument

その他、~/catkin_ws/src/beginner_tutorials下にコピーして、
$ catkin build
$ source ~/catkin_ws/devel/setup.bash
$ roscd beginner_tutorials
ののちに、
$ roslaunch beginner_tutorials turtlebot_checkerboard.launch
や
$ roslaunch ./turtlebot_checkerboard.launch
などと試したのですが、同じようなエラーが出て実行できませんでした。

... logging to /home/mech-user/.ros/log/4770aa0c-1d0a-11eb-8e48-2079185f7e13/roslaunch-ki00118-3479.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

Deprecated: xacro tag 'kobuki' w/o 'xacro:' xml namespace prefix (will be forbidden in Noetic)
when processing file: /home/mech-user/catkin_ws/src/robot-programming/dxl_armed_turtlebot/urdf/robot.urdf.xacro
Use the following command to fix incorrect tag usage:
find . -iname "*.xacro" | xargs sed -i 's#<\([/]\?\)\(if\|unless\|include\|arg\|property\|macro\|insert_block\)#<\1xacro:\2#g'

xacro.py is deprecated; please use xacro instead
started roslaunch server http://ki00118:45851/

SUMMARY
========

PARAMETERS
 * /camera/rgb/display: 1
 * /camera/rgb/frame_id: camera_rgb_optica...
 * /camera/rgb/grid0_size_x: 7
 * /camera/rgb/grid0_size_y: 4
 * /camera/rgb/objectdetection_tf_publisher/use_simple_tf: True
 * /camera/rgb/rect0_size_x: 0.02
 * /camera/rgb/rect0_size_y: 0.02
 * /camera/rgb/rotation0: 1.0 0.0 0.0 0.0 -...
 * /camera/rgb/single: 1
 * /camera/rgb/translation0: 0 0 0
 * /camera/rgb/type0: test_object
 * /cmd_vel_mux/yaml_cfg_file: /home/mech-user/c...
 * /depthimage_to_laserscan/output_frame_id: /camera_depth_frame
 * /depthimage_to_laserscan/range_min: 0.45
 * /depthimage_to_laserscan/scan_height: 10
 * /fullbody_controller/action_monitor_rate: 100
 * /fullbody_controller/constraints/arm_joint1/goal: 0.02
 * /fullbody_controller/constraints/arm_joint2/goal: 0.02
 * /fullbody_controller/constraints/arm_joint3/goal: 0.02
 * /fullbody_controller/constraints/arm_joint4/goal: 0.02
 * /fullbody_controller/constraints/arm_joint5/goal: 0.02
 * /fullbody_controller/constraints/arm_joint6/goal: 0.02
 * /fullbody_controller/constraints/goal_time: 0.5
 * /fullbody_controller/constraints/stopped_velocity_tolerance: 0.02
 * /fullbody_controller/gains/arm_joint1/d: 0.0
 * /fullbody_controller/gains/arm_joint1/i: 0.0
 * /fullbody_controller/gains/arm_joint1/p: 25.0
 * /fullbody_controller/gains/arm_joint2/d: 0.0
 * /fullbody_controller/gains/arm_joint2/i: 0.0
 * /fullbody_controller/gains/arm_joint2/p: 25.0
 * /fullbody_controller/gains/arm_joint3/d: 0.0
 * /fullbody_controller/gains/arm_joint3/i: 0.0
 * /fullbody_controller/gains/arm_joint3/p: 25.0
 * /fullbody_controller/gains/arm_joint4/d: 0.0
 * /fullbody_controller/gains/arm_joint4/i: 0.0
 * /fullbody_controller/gains/arm_joint4/p: 25.0
 * /fullbody_controller/gains/arm_joint5/d: 0.0
 * /fullbody_controller/gains/arm_joint5/i: 0.0
 * /fullbody_controller/gains/arm_joint5/p: 25.0
 * /fullbody_controller/gains/arm_joint6/d: 0.0
 * /fullbody_controller/gains/arm_joint6/i: 0.0
 * /fullbody_controller/gains/arm_joint6/p: 25.0
 * /fullbody_controller/joints: ['arm_joint1', 'a...
 * /fullbody_controller/state_publish_rate: 100
 * /fullbody_controller/stop_trajectory_duration: 0
 * /fullbody_controller/type: velocity_controll...
 * /gazebo/enable_ros_network: True
 * /gripper_controller/action_monitor_rate: 100
 * /gripper_controller/constraints/goal_time: 0.5
 * /gripper_controller/constraints/gripper_joint/goal: 0.02
 * /gripper_controller/constraints/stopped_velocity_tolerance: 0.02
 * /gripper_controller/gains/gripper_joint/d: 0.0
 * /gripper_controller/gains/gripper_joint/i: 0.0
 * /gripper_controller/gains/gripper_joint/p: 10.0
 * /gripper_controller/joints: ['gripper_joint']
 * /gripper_controller/state_publish_rate: 100
 * /gripper_controller/stop_trajectory_duration: 0
 * /gripper_controller/type: velocity_controll...
 * /joint_state_controller/publish_rate: 50
 * /joint_state_controller/type: joint_state_contr...
 * /robot_description: <?xml version="1....
 * /robot_state_publisher/publish_frequency: 30.0
 * /rosdistro: melodic
 * /rosversion: 1.14.9
 * /use_sim_time: True

NODES
  /
    cmd_vel_mux (nodelet/nodelet)
    cmd_vel_renamer (topic_tools/relay)
    controller_spawner (controller_manager/spawner)
    depthimage_to_laserscan (depthimage_to_laserscan/depthimage_to_laserscan)
    gazebo (gazebo_ros/gzserver)
    gazebo_gui (gazebo_ros/gzclient)
    mobile_base_nodelet_manager (nodelet/nodelet)
    robot_state_publisher (robot_state_publisher/robot_state_publisher)
    rviz (rviz/rviz)
    teleop_twist_keyboard (teleop_twist_keyboard/teleop_twist_keyboard.py)
    tuck_arm (dxl_armed_turtlebot/tuck_arm.py)
    urdf_spawner (gazebo_ros/spawn_model)
  /camera/rgb/
    checkerboard_detector (checkerboard_detector/checkerboard_detector)
    objectdetection_tf_publisher (checkerboard_detector/objectdetection_tf_publisher.py)

WARNING: unrecognized tag sphinxdoc
ROS_MASTER_URI=http://localhost:11311

process[robot_state_publisher-1]: started with pid [3497]
process[cmd_vel_renamer-2]: started with pid [3498]
process[rviz-3]: started with pid [3504]
process[gazebo-4]: started with pid [3510]
process[gazebo_gui-5]: started with pid [3515]
process[urdf_spawner-6]: started with pid [3521]
process[depthimage_to_laserscan-7]: started with pid [3522]
process[mobile_base_nodelet_manager-8]: started with pid [3523]
process[cmd_vel_mux-9]: started with pid [3528]
process[controller_spawner-10]: started with pid [3531]
process[tuck_arm-11]: started with pid [3533]
process[camera/rgb/checkerboard_detector-12]: started with pid [3538]
process[camera/rgb/objectdetection_tf_publisher-13]: started with pid [3541]
RLException: Roslaunch got a 'No such file or directory' error while attempting to run:

xterm -e /opt/ros/melodic/lib/teleop_twist_keyboard/teleop_twist_keyboard.py __name:=teleop_twist_keyboard __log:=/home/mech-user/.ros/log/4770aa0c-1d0a-11eb-8e48-2079185f7e13/teleop_twist_keyboard-14.log

Please make sure that all the executables in this command exist and have
executable permission. This is often caused by a bad launch-prefix.
The traceback for the exception was written to the log file
[teleop_twist_keyboard-14] killing on exit
[camera/rgb/objectdetection_tf_publisher-13] killing on exit
Traceback (most recent call last):
  File "/opt/ros/melodic/lib/checkerboard_detector/objectdetection_tf_publisher.py", line 2, in <module>
    import rospy
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/__init__.py", line 47, in <module>
    from std_msgs.msg import Header
  File "/opt/ros/melodic/lib/python2.7/dist-packages/std_msgs/msg/__init__.py", line 5, in <module>
    from ._ColorRGBA import *
  File "/opt/ros/melodic/lib/python2.7/dist-packages/std_msgs/msg/_ColorRGBA.py", line 2, in <module>
    """autogenerated by genpy from std_msgs/ColorRGBA.msg. Do not edit."""
KeyboardInterrupt
[camera/rgb/checkerboard_detector-12] killing on exit
[tuck_arm-11] killing on exit
Traceback (most recent call last):
  File "/home/mech-user/catkin_ws/src/robot-programming/dxl_armed_turtlebot/scripts/tuck_arm.py", line 4, in <module>
    import rospy
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/__init__.py", line 49, in <module>
[cmd_vel_mux-9] killing on exit
    from .client import spin, myargv, init_node, \
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/client.py", line 49, in <module>
    import rosgraph
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rosgraph/__init__.py", line 36, in <module>
    from . masterapi import Master, MasterFailure, MasterError, MasterException
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rosgraph/masterapi.py", line 41, in <module>
    from xmlrpc.client import ServerProxy  # Python 3.x
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rosgraph/xmlrpc.py", line 60, in <module>
    from SimpleXMLRPCServer import SimpleXMLRPCServer #Python 2.x
  File "/usr/lib/python2.7/SimpleXMLRPCServer.py", line 102, in <module>
[depthimage_to_laserscan-7] killing on exit
[gazebo_gui-5] killing on exit
[controller_spawner-10] killing on exit
[urdf_spawner-6] killing on exit
Traceback (most recent call last):
  File "/opt/ros/melodic/lib/controller_manager/spawner", line 38, in <module>
    import rospy, sys
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/__init__.py", line 47, in <module>
    from std_msgs.msg import Header
  File "/opt/ros/melodic/lib/python2.7/dist-packages/std_msgs/msg/__init__.py", line 26, in <module>
    from ._UInt16MultiArray import *
  File "/opt/ros/melodic/lib/python2.7/dist-packages/std_msgs/msg/_UInt16MultiArray.py", line 2, in <module>
    """autogenerated by genpy from std_msgs/UInt16MultiArray.msg. Do not edit."""
KeyboardInterrupt
[mobile_base_nodelet_manager-8] killing on exit
Traceback (most recent call last):
  File "/opt/ros/melodic/bin/catkin_find", line 57, in <module>
    main()
  File "/opt/ros/melodic/bin/catkin_find", line 38, in main
    args = parse_args()
  File "/opt/ros/melodic/bin/catkin_find", line 19, in parse_args
    parser.add_argument('--first-only', action='store_true', help='Flag if only the first result should be returned')
  File "/usr/lib/python2.7/argparse.py", line 1308, in add_argument
    import xmlrpclib
  File "/usr/lib/python2.7/xmlrpclib.py", line 145, in <module>
    import httplib
  File "/usr/lib/python2.7/httplib.py", line 80, in <module>
    import mimetools
  File "/usr/lib/python2.7/mimetools.py", line 1, in <module>
    """Various tools used by MIME-reading or MIME-writing programs."""
KeyboardInterrupt
    self._get_formatter()._format_args(action, None)
  File "/usr/lib/python2.7/argparse.py", line 2331, in _get_formatter
    return self.formatter_class(prog=self.prog)
  File "/usr/lib/python2.7/argparse.py", line 163, in __init__
    width = int(_os.environ['COLUMNS'])
  File "/usr/lib/python2.7/UserDict.py", line 38, in __getitem__
    if hasattr(self.__class__, "__missing__"):
KeyboardInterrupt
[gazebo-4] killing on exit
[rviz-3] killing on exit
Traceback (most recent call last):
Traceback (most recent call last):
  File "/opt/ros/melodic/bin/catkin_find", line 57, in <module>
      File "/opt/ros/melodic/lib/gazebo_ros/spawn_model", line 29, in <module>
main()
  File "/opt/ros/melodic/bin/catkin_find", line 42, in main
    results = find_in_workspaces(args.install_folders, args.project, args.path, first_matching_workspace_only=args.without_underlays, first_match_only=args.first_only, considered_paths=checked)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/catkin/find_in_workspaces.py", line 149, in find_in_workspaces
    source_path_to_packages[source_path] = find_packages(source_path)
  File "/usr/lib/python2.7/dist-packages/catkin_pkg/packages.py", line 87, in find_packages
        packages = find_packages_allowing_duplicates(basepath, exclude_paths=exclude_paths, exclude_subspaces=exclude_subspaces, warnings=warnings)
  File "/usr/lib/python2.7/dist-packages/catkin_pkg/packages.py", line 148, in find_packages_allowing_duplicates
from gazebo_ros import gazebo_interface
  File "/opt/ros/melodic/lib/python2.7/dist-packages/gazebo_ros/gazebo_interface.py", line 9, in <module>
        from gazebo_msgs.msg import *
  File "/opt/ros/melodic/lib/python2.7/dist-packages/gazebo_msgs/msg/__init__.py", line 1, in <module>
    from ._ContactState import *
  File "/opt/ros/melodic/lib/python2.7/dist-packages/gazebo_msgs/msg/_ContactState.py", line 9, in <module>
xml, filename=filename, warnings=warnings)
    import geometry_msgs.msg
  File "/opt/ros/melodic/lib/python2.7/dist-packages/geometry_msgs/msg/__init__.py", line 3, in <module>
    from ._AccelWithCovariance import *
  File "/opt/ros/melodic/lib/python2.7/dist-packages/geometry_msgs/msg/_AccelWithCovariance.py", line 2, in <module>
      File "/usr/lib/python2.7/dist-packages/catkin_pkg/package.py", line 666, in parse_package_string
"""autogenerated by genpy from geometry_msgs/AccelWithCovariance.msg. Do not edit."""
KeyboardInterrupt
    pkg.build_export_depends.append(deepcopy(d))
  File "/usr/lib/python2.7/copy.py", line 190, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/usr/lib/python2.7/copy.py", line 328, in _reconstruct
    args = deepcopy(args, memo)
  File "/usr/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python2.7/copy.py", line 237, in _deepcopy_tuple
    y.append(deepcopy(a, memo))
  File "/usr/lib/python2.7/copy.py", line 193, in deepcopy
    _keep_alive(x, memo) # Make sure x lives at least as long as d
  File "/usr/lib/python2.7/copy.py", line 279, in _keep_alive
    except KeyError:
KeyboardInterrupt
[cmd_vel_renamer-2] killing on exit
[robot_state_publisher-1] killing on exit

**Comment by k-okada** [comment]
```
xterm -e /opt/ros/melodic/lib/teleop_twist_keyboard/teleop_twist_keyboard.py __name:=teleop_twist_keyboard __log:=/home/mech-user/.ros/log/4770aa0c-1d0a-11eb-8e48-2079185f7e13/teleop_twist_keyboard-14.log

Please make sure that all the executables in this command exist and have
executable permission. This is often caused by a bad launch-prefix.
```
とあるので，`xterm`というコマンドがあるか確認．なければ，
```
$ sudo apt install xterm
```
かな．
