### ISSUE TITLE
viewerを立ち上げた後pythonプログラムが動きません

### ISSUE THREAD

**Issue by tsu-K** [jsk-enshu/robot-programming#93]
```
Traceback (most recent call last):
  File "image_view2.py", line 5, in <module>
    from image_view2.msg import ImageMarker2
  File "/home/mech-user/catkin_ws/src/robot-programming/dxl_armed_turtlebot/scripts/image_view2.py", line 5, in <module>
    from image_view2.msg import ImageMarker2
ImportError: No module named msg
mech-user@test1-pc:~/catkin_ws/src/robot-programming/dxl_armed_turtlebot/scripts$ python image_view2.py
Traceback (most recent call last):
  File "image_view2.py", line 5, in <module>
    from image_view2.msg import ImageMarker2
  File "/home/mech-user/catkin_ws/src/robot-programming/dxl_armed_turtlebot/scripts/image_view2.py", line 5, in <module>
    from image_view2.msg import ImageMarker2
ImportError: No module named msg
```

**Comment by tsu-K** [comment]
解決しました
pythonのファイル名をimportするmsgファイルの名前と同じにしていたのが原因だったようです
